fix: use latest "obsidian" package
not from github

to fix:

    ❯ npm run build

    > obsidian-plugin-open-that-day@0.3.3 build
    > tsc -noEmit -skipLibCheck && node esbuild.config.mjs production

    src/main.ts:98:4 - error TS2322: Type 'import("/Users/nagata-hiroaki/src/github.com/handlename/obsidian-plugin-open-that-day/node_modules/obsidian-daily-notes-interface/node_modules/obsidian/obsidian").TFile' is not assignable to type 'import("/Users/nagata-hiroaki/src/github.com/handlename/obsidian-plugin-open-that-day/node_modules/obsidian/obsidian").TFile'.
    Types of property 'vault' are incompatible.
        Type 'Vault' is missing the following properties from type 'Vault': getFileByPath, getFolderByPath, getAllFolders

    98    file = await createDailyNote(day);
        ~~~~

    Found 1 error in src/main.ts:98